bot:
  token: '5853188901:AAGdOjZEZOYmtE-FWrX-5zM7UnEjN5ra6PM'

spring:
  datasource:
    url: 'jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}'
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate.ddl-auto: update

  sql:
    init:
      node: always
