bot:
  token: '5853188901:AAGdOjZEZOYmtE-FWrX-5zM7UnEjN5ra6PM'

spring:
  datasource:
    url: 'postgresql://postgres:wbzneJ0KjUymRLcON8Xf@containers-us-west-125.railway.app:7400/railway'
    username: 'postgres'
    password: 'wbzneJ0KjUymRLcON8Xf'
    driverClassName: 'org.postgresql.Driver'
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
